/**
 * Ground tiles, 16x16, one set per biome `tile` id. Frames are variants the
 * renderer picks per cell by hash; each tiles seamlessly (no feature touches
 * an edge except the sea's wrapping wave dashes).
 */
import { WORLD_PALETTE } from '../palette.ts'
import type { Picture } from '../types.ts'

export const TILES: Readonly<Record<string, Picture>> = {
  'sea': {
    id: 'sea',
    width: 16,
    height: 16,
    palette: WORLD_PALETTE,
    frames: [
      [
        'bbbbbbbbbabbbbbb',
        'bcbbbbbbbbbbbbbb',
        'bbdbabbbabbbbbbb',
        'bbbbbbbcbbbbabbb',
        'abbabbbbbbbbabbb',
        'bbbbbbabbbbbbaba',
        'bbbbbbbbbcccbabb',
        'bbbbbbbbbbabbbbb',
        'bbbbdbbccccbbcbb',
        'bcbbbabbabbbbbbb',
        'bbbbcbbbbbbbbbbb',
        'cbbbbbbbbbbbbbbb',
        'bbbbbbbbccbbbbba',
        'bcccccbbabbbbbbb',
        'bbbcccbbbbbbbbbb',
        'babbabbbbabbbbbb',
      ],
      [
        'bbbbbbbbbbabbbbb',
        'bbbbbbbbcbbbbbbb',
        'bbaabbbbbccccccb',
        'bbabbbbbabababbb',
        'cccabbcbbbbbbbbb',
        'babbbbbbbbbbbbbb',
        'bcbbbabbbababbbb',
        'bbbbbabbbbbbbbbb',
        'babdbcbbbbbbbbbb',
        'bbbbbbbbbbbbbcbb',
        'bbbbbbbbbbbbbbbb',
        'bacbbbbbbbccccbb',
        'cbdbbbbcbbbacccc',
        'bbbbbbbabbabbabb',
        'acbbabbabbbbbbbb',
        'bbbbbbbabbbbbbbb',
      ],
      [
        'ccbbbbbbbabbbbcc',
        'bbbbbbccccbcccba',
        'cbbbbbbabbbbabbb',
        'babbbbbbbcbbbbbb',
        'bbbbbbbbbbbbbbbb',
        'bababbbbcbbbbbbb',
        'bbbbbbbbbbbcbbab',
        'bbbbbbbbbcbbbbbb',
        'bbbbbbdbbbbbbbbb',
        'bbbbbabbbbbbbbab',
        'bbbbbbbbbcbbbbbb',
        'abbbbbbbbbbbbbbb',
        'bbbabaabbbbabbbb',
        'cccbbbbbabbabbcc',
        'bbbabbbbbbaabbbd',
        'abbbbbbabbbabbbb',
      ],
    ],
  },
  'sand': {
    id: 'sand',
    width: 16,
    height: 16,
    palette: WORLD_PALETTE,
    frames: [
      [
        'ffffffffffffffff',
        'fffhffhffffhffff',
        'ffgfffffffffffff',
        'iffgfgffhfffffff',
        'fffhfggfghffffff',
        'fgffffffffhfffgf',
        'hffffffffffhfiff',
        'fhffgfffffffffff',
        'ffgfffffffgffgff',
        'fffffffffffffffg',
        'ffffffffffffffff',
        'fffffffffffgffff',
        'ffgffffgfffgffff',
        'fffffifffffffffi',
        'ffffffffgfffffff',
        'ffffffffffffffff',
      ],
      [
        'ffgffffhffffffff',
        'ffffffffghhfffff',
        'ffffffgfffgfffff',
        'ffffffffffffffff',
        'fffggfffffhgffff',
        'ffffffffffghffff',
        'fffffffffffffgff',
        'ffhffffffgffffgf',
        'fffiffffffffgfff',
        'ffifffgfhfffffff',
        'ffffffffffffffff',
        'hffffffifffffgff',
        'ffffhfffffffffff',
        'ffffffffffffffff',
        'fffffhfffgffffhf',
        'ffffgffiffffffff',
      ],
      [
        'ffgfhiffffffffff',
        'fffffffffffffffg',
        'ffffhfffffffffgg',
        'fgffffffffffgfff',
        'hfffhfffffffffff',
        'fhffffffgfffffff',
        'fffgffffffgfffff',
        'ffffffhfffffffff',
        'fhhififgffffffff',
        'hffffffffhgfffff',
        'fffffffffffffffh',
        'ffffffffffffffff',
        'ffffffffffffffff',
        'ffffgfffhffffgff',
        'ffifgfffffffffff',
        'fffffffffghfffff',
      ],
    ],
  },
  'grass': {
    id: 'grass',
    width: 16,
    height: 16,
    palette: WORLD_PALETTE,
    frames: [
      [
        'jjjjjkkjkljkjjjk',
        'jkjjjjjjjjjjjjjj',
        'ljjjjjkjkjjkjjjj',
        'jjjjjjjjjjjjjjjj',
        'jjljjjkjjjjkjjjj',
        'jjjjjjjjkjjjjjjj',
        'jjkjljjjjjljjjjj',
        'jjjlmjjljjjkjjjj',
        'kjjmkjjjkjjjjjjj',
        'jjjjjjjjjljjkjjj',
        'jjjljjjjjmjkjjjj',
        'jjjmjljjjmjkjjjk',
        'ljjjjjjjkjjjkjjj',
        'mljjjjjjjjjkjjlj',
        'jmjkjjjjjjjjjjjj',
        'jjjjjljjjjjjjjkj',
      ],
      [
        'ljljjljjkjkjljjj',
        'kjjjjkjjjjjjjjjj',
        'ljjjjjjjjjjjljjj',
        'jjjjjjjjljjjjljj',
        'jjkjjjjjjjljljjj',
        'jjjjjjjjljmlmjjl',
        'jjjjjjjjjkjjjjjm',
        'kjjjjjjjjljjjjjj',
        'jjjjkjjjjmjjjjjk',
        'jjjjjjjjjjjjjjkj',
        'jjjkjkjjjjjjkjjk',
        'jljjjjjjjjjjjjjj',
        'kkjjjjjjljjjjkll',
        'jjkjjjjjmjljjjmj',
        'jljjjjjljjjjjjjj',
        'kmjjjljjjjkjjjjj',
      ],
      [
        'jljjjkjjkjjjkjjj',
        'jmjkjjjjjjjjljjj',
        'jjjjjjjjkjjjmjjj',
        'jjjjjkkjjjjjjjjj',
        'jkkjjlkjjjjkjjjj',
        'jjjjlmjjjjljjjjj',
        'jjjjjljjjjjkjjkj',
        'ljjjjmljjjjjjjlj',
        'mjkjjjjjjjjjjjjj',
        'jjjkljjjjjkjjjjj',
        'jjjjllljjjjjjjjj',
        'jjjkjmjjjjjjjjkj',
        'jjjjjjjjjljjjjjk',
        'jjjjkljjjmjjljjj',
        'jjljjjjjjjljjjjj',
        'jjjjkkjjjjjjkkkj',
      ],
    ],
  },
  'forest': {
    id: 'forest',
    width: 16,
    height: 16,
    palette: WORLD_PALETTE,
    frames: [
      [
        'nnnnnnnnnqqonnnq',
        'nnnnnnnnqqonnnpn',
        'nnnnnnnonpnonnnn',
        'onnnnnqnnonpnnnn',
        'ononpnnnnnnnnqpn',
        'nnnnnpqqnnqnnnnn',
        'nnonnnnnnnpnpnqn',
        'nonnnpnnnnnnnnnn',
        'nnnqqnnnnnnnnnno',
        'nnnnnnonnnnnqnnn',
        'pnnonnonnnonnnnn',
        'ppqnnnnnnnnnnnnn',
        'nnqnnonnqqonnonn',
        'nnnonpnnnnnnnnnn',
        'nnnnnpnnonnnnpnn',
        'nnonnnnnnnnnnnqq',
      ],
      [
        'nnnnnoonnnnonnnn',
        'pnnqqnpnnnnnopnn',
        'nononqnnnnnnnnon',
        'nnonnnnnpnnnqopn',
        'nnonnnnnnnnonnnn',
        'nnnnnnpnnqpnnnnn',
        'qqnnonnnonnonnnn',
        'nnnnnnnnnnnnnnnn',
        'nnononnnnnnnpnnn',
        'nnnnnnnnnoonnnnn',
        'nnnnnqqnnnnnnnnn',
        'nonnnnppnnqpnnno',
        'nqqnpnnnnnnnpnnn',
        'nnqnnnnnqnnnnnoq',
        'nonnnnnnnnnnoqqn',
        'nnnnqnnnnoonnnnn',
      ],
      [
        'nnonnnnppnnnnnnn',
        'onnnnnnnnnnnnnpn',
        'nnnnnnnnnnnnnnnp',
        'nnnnnpnnnonnoqnn',
        'nnnnonnnnnnnonnn',
        'onnnqnnnpnnopnnn',
        'nnpnnpnqqnnnnnno',
        'qqnnnnnnnnnnqqnn',
        'nnnnnnnpnnnpnnon',
        'nnnnnqnnnnnnonnn',
        'nnnononnnnpnnnqq',
        'nnnnnnnonnonnqnn',
        'nnonnqnqnpnnnnnq',
        'nnnnnnnnnnnnnnno',
        'nnnpnnnnnnnnqqnn',
        'nnonnnnnnnnnnnno',
      ],
    ],
  },
  'heath': {
    id: 'heath',
    width: 16,
    height: 16,
    palette: WORLD_PALETTE,
    frames: [
      [
        'rrrrrrrtvrrssrrr',
        'rrrrrrrrrrttrsur',
        'rrrrrrrrrrrvrrrr',
        'rrsrrsrrrsrrrrrr',
        'rrrsrtsrrrrurrrr',
        'ttrrrrrrrrrrrrsr',
        'rrrrrsrrvrrtrrrt',
        'rrrrrurrsrrrrrrr',
        'rrrrurrrrrrrrrrs',
        'rrrrvrrurrvrrrrs',
        'rtrrrrrrrrrrrrrr',
        'rsrrrrrrrrsrrrrr',
        'rrrrrtrrrrsrtrrr',
        'rsrurrurrsrrrrrr',
        'rrvrrtrrrrtrrrrr',
        'rssrrrtrtsrrrtrr',
      ],
      [
        'rsrrtrtrrrrrrrrr',
        'rrrrrrrrrrrutrrr',
        'rrtrrvrrrrrrrrrr',
        'rrrvrsrrrrtrsrrr',
        'rrrrrrrrrrrrssrr',
        'rurrrurrrrsrsrrs',
        'rrrrrsrrrrrtrtrr',
        'rrrsrrrrrrtrrrrr',
        'rrrtrrrrrrrrrrrr',
        'rrrrrrrrrrrtrrrr',
        'srtrstrrsrrrrvtr',
        'tusrrsrrrrvvrrtr',
        'trrrsrrsrrrrrrru',
        'srrrrrrrrrturrrr',
        'rrvrrrurrurrsrrr',
        'rtrsrrrtrrrrrrtr',
      ],
      [
        'rrrrrrrrrrrrrrrr',
        'rrrrrtrrrrtrrrrs',
        'rrrrstrrrrsrsrtr',
        'rruurrrrrrutssrr',
        'rrrsrrrurrrrrrrr',
        'urrtrrrrrrrurvrr',
        'rrrrsrusrrrrurrr',
        'trrrrsrrrrsttsrr',
        'rrssrrrrsrttrrrr',
        'rrrrrrrrrrrrrurr',
        'rrrssurrttrrtrrt',
        'srrvrrrrrrrrrrru',
        'srtsrrrrrrrtrrrt',
        'rrrrrrrrrrrrrrrr',
        'trrrrurrrrtrrrsr',
        'rrrrrrtrrrrrrrrr',
      ],
    ],
  },
  'stone': {
    id: 'stone',
    width: 16,
    height: 16,
    palette: WORLD_PALETTE,
    frames: [
      [
        'wwwwxwwwwwwwzwwx',
        'wwwwwxwyxwzzwwww',
        'wwwwwwwwwyyywyww',
        'wwwwwwwwwwwxwwww',
        'wwwywwwwwwwwwwww',
        'wwwwxwwwwwwwwwzw',
        'wwwwwyxwwwwwzzww',
        'wwwwwwwywwzzwwww',
        'wywwwwwwwwwwxwww',
        'zwwwwwywwwywwwxw',
        'wxwwwwwwwwwwwwwy',
        'wwwwwwwwwwwwxwwy',
        'wywwwwwwwwzwwwyw',
        'wwwwwxwwzwwwwwww',
        'wwwwwwwwwwwyxwyw',
        'ywwwwwwwwwxwwwww',
      ],
      [
        'wwwwwwwwwxwwwzww',
        'wwxwzwywwxwwwwww',
        'wwwwwwwwwwwwwwww',
        'wwwwwwwwwwwwwwww',
        'wwwwwwwzwwwwwwxw',
        'xwwwwwwwzwwwwwww',
        'wwwwzwwwxwxwxwxw',
        'wwzwwzwwwxwwwwyw',
        'wwwwwwzywwwwxyww',
        'wwwyxwwxwwwxwwww',
        'wwwywxwwwwwwwwww',
        'wywwwwwwxwwwwyww',
        'wwwwwwwwwwwwwwww',
        'wwwwwwwwwywwwxxw',
        'wwwwwxwwwwwwwwww',
        'wwwwwxwwwywwywww',
      ],
      [
        'yywzxxwwwxwwwwww',
        'wwxwwwwwwwwwwwxw',
        'wwwwwwwwwwwxwwww',
        'xwwzwwwwywwwwwwy',
        'wwywwwwwzwwwwwxx',
        'wwwwywwwxwwwwwww',
        'xwwxwwwzwwwxwwww',
        'wwwwwwwwwwxwwzzw',
        'wwwwwwwwwwxwwzzz',
        'wwwxwwwwwwxwwxww',
        'wwwwwwwwwwwwwwww',
        'wwwwywwxwxwwwxwy',
        'wxwwzwwwwywwwwxw',
        'wwwwwwwwwwwwwwwx',
        'wwzwzwwwwwwwywww',
        'wwwzwzwwwwwwwwww',
      ],
    ],
  },
}
