// The one BUILD_ID (CLAUDE.md 3.6 rule 6): git short SHA + UTC build time,
// computed once per build and handed to every package that stamps it. No
// human or agent edits a version number.
//
// Pure helpers only; `cli.ts` does the git call, the file write and the spawn.

/** `<sha>-<yyyymmddThhmmssZ>`, e.g. `2ad089b-20260928T141503Z`. `nogit` when built outside a checkout. */
export const BUILD_ID_PATTERN = /^(?:[0-9a-f]{7,40}|nogit)-\d{8}T\d{6}Z$/

/** The env var that carries the id from `cli.ts` to Vite (and anything else it spawns). */
export const BUILD_ID_ENV = 'BUILD_ID'

/** Where the generated server const lives, relative to the repo root. Git-ignored. */
export const SERVER_BUILD_ID_FILE = 'packages/server/src/build-id.ts'

/** Compact UTC timestamp: `2026-09-28T14:15:03.120Z` -> `20260928T141503Z`. */
export function utcStamp(at: Date): string {
  return `${at.toISOString().slice(0, 19).replace(/[-:]/g, '')}Z`
}

export function formatBuildId(sha: string | undefined, at: Date): string {
  const id = `${sha?.trim().toLowerCase() || 'nogit'}-${utcStamp(at)}`
  if (!BUILD_ID_PATTERN.test(id)) throw new Error(`not a build id: ${id}`)
  return id
}

/**
 * The id for this build: an inherited `BUILD_ID` wins (so a nested build, or
 * CI stamping once for several jobs, reuses it), otherwise a fresh one.
 */
export function resolveBuildId(env: Record<string, string | undefined>, sha: () => string | undefined, now: () => Date): string {
  const inherited = env[BUILD_ID_ENV]
  if (inherited !== undefined && inherited !== '') {
    if (!BUILD_ID_PATTERN.test(inherited)) throw new Error(`${BUILD_ID_ENV}=${inherited} is not a build id`)
    return inherited
  }
  return formatBuildId(sha(), now())
}

/** Source of the generated `packages/server/src/build-id.ts`. */
export function serverModuleSource(id: string): string {
  if (!BUILD_ID_PATTERN.test(id)) throw new Error(`not a build id: ${id}`)
  return [
    '// GENERATED by tools/build-id at build time; git-ignored. Never edit.',
    `export const BUILD_ID = '${id}'`,
    '',
  ].join('\n')
}
