/**
 * Props the player makes: the stump a felled pine leaves, the bare bush a
 * picked juniper leaves, and the campfire
 * (3 frames of flame, played in a loop by the renderer). Anchored bottom-centre
 * on their cell like every prop.
 */
import { WORLD_PALETTE } from '../palette.ts'
import type { Picture } from '../types.ts'

export const CAMP_ART: Readonly<Record<string, Picture>> = {
  'stump': {
    id: 'stump',
    width: 16,
    height: 16,
    palette: WORLD_PALETTE,
    frames: [
      [
        '................',
        '................',
        '................',
        '................',
        '................',
        '......KKKK......',
        '....KKIIIIKK....',
        '...KIIGIIGIIK...',
        '...KIIIGGIIIK...',
        '...KTIIIIIITK...',
        '...KTTUUUUTTK...',
        '...KTTUUUUTTK...',
        '..KKTTUUUUTTKK..',
        '.KUTTTTTTTTTTUK.',
        '..KKKKKKKKKKKK..',
        '................',
      ],
    ],
  },
  'campfire': {
    id: 'campfire',
    width: 16,
    height: 24,
    palette: WORLD_PALETTE,
    frames: [
      [
        '................',
        '................',
        '................',
        '.....K..........',
        '....KMK.........',
        '.....K..........',
        '................',
        '........K.......',
        '......KKOK......',
        '.....KOOOK......',
        '.....KOOOK......',
        '.....KOOOKK.....',
        '.....KONNOOK....',
        '.....KONNOOK....',
        '....KKOMMOOK....',
        '...KOONZZNOK....',
        '...KOONZZNOK....',
        '...KOONZZNOHKK..',
        '..KwHHHGHGGGwwK.',
        '..KHHHGHGHGGGxK.',
        '.KwGGGKKKKHHHwK.',
        '.KxxwwKKKKwwxxK.',
        '..KKxxKwwKxxKK..',
        '....KKKxxKKK....',
      ],
      [
        '................',
        '................',
        '................',
        '................',
        '................',
        '..........K.....',
        '.........KMK....',
        '........KOK.....',
        '.......KONOK....',
        '.......KONOK....',
        '......KKONOK....',
        '.....KONNNOK....',
        '.....KONNNOK....',
        '.....KONNNOK....',
        '.....KOMMNOK....',
        '....KONZZNNOK...',
        '....KONZZNNOK...',
        '...KOONZZNOHKK..',
        '..KwHHHGHGGGwwK.',
        '..KHHHGHGHGGGxK.',
        '.KwGGGKKKKHHHwK.',
        '.KxxwwKKKKwwxxK.',
        '..KKxxKwwKxxKK..',
        '....KKKxxKKK....',
      ],
      [
        '................',
        '................',
        '......K.........',
        '.....KMK........',
        '......K.........',
        '................',
        '................',
        '................',
        '......K.........',
        '.....KOK........',
        '....KONOK.......',
        '....KONOK.......',
        '.....KONOK......',
        '....KONNNOK.....',
        '....KONNNOK.....',
        '...KONNMMNOK....',
        '...KONNZZNOK....',
        '...KOONZZNOHKK..',
        '..KwHHHGHGGGwwK.',
        '..KHHHGHGHGGGxK.',
        '.KwGGGKKKKHHHwK.',
        '.KxxwwKKKKwwxxK.',
        '..KKxxKwwKxxKK..',
        '....KKKxxKKK....',
      ],
    ],
  },
  'bush.bare': {
    id: 'bush.bare',
    width: 16,
    height: 16,
    palette: WORLD_PALETTE,
    frames: [
      [
        '................',
        '................',
        '................',
        '................',
        '................',
        '.....KKKKKK.....',
        '...KKllllljKK...',
        '..KlkllljjjjjK..',
        '.KllllmkjjjjjjK.',
        '.KllllkjjjjmjmK.',
        '.KllljjjjkjjmmK.',
        '.KljjjjjjmmmmmK.',
        '.KjjjjjjjmmmmmK.',
        '..KmmkmmmmmmmK..',
        '...KKmmmmmmKK...',
        '.....KKKKKK.....',
      ],
    ],
  },
}
