/**
 * Props standing on the ground, drawn y-sorted with characters. Each is
 * anchored bottom-centre on its footprint's bottom edge: a pine's trunk sits
 * in its cell, and the wreck lies across its 4x2 cells.
 */
import { WORLD_PALETTE } from '../palette.ts'
import type { Picture } from '../types.ts'

export const PROP_ART: Readonly<Record<string, Picture>> = {
  'pine': {
    id: 'pine',
    width: 24,
    height: 40,
    palette: WORLD_PALETTE,
    frames: [
      [
        '............K...........',
        '...........KRK..........',
        '...........KRPK.........',
        '..........KRPQK.........',
        '.........KRRPQQK........',
        '.........KRSPQQK........',
        '.........KRRPQQK........',
        '........KRRPPPQQK.......',
        '.......KRSRPPPQQQK......',
        '.......KRRRPPPQQQK......',
        '.......KRRRPPPQQQK......',
        '......KRSRRPPPPQQQK.....',
        '.....KRRRRPPPPPQQQQK....',
        '.....KRRRRPPPPPQQQQK....',
        '.....KQSQQQQQQQQQQQK....',
        '....KQQQQQQQQQQQQQQQK...',
        '.....KKRRRRPPPPQQQKK....',
        '......KRRRRPPPPQQQK.....',
        '.....KRSRRPPPPPQQQQK....',
        '....KRRRRRPPPPPQQQQQK...',
        '....KRRRRRPPPPPQQQQQK...',
        '...KRSRRRRPPPPPPQQQQQK..',
        '...KQQQQQQQQQQQQQQQQQK..',
        '..KQQQQQQQQQQQQQQQQQQQK.',
        '...KKKRRRRPPPPPQQQQKKK..',
        '.....KRSRRPPPPPQQQQK....',
        '....KRRRRRPPPPPQQQQQK...',
        '...KRRRRRRPPPPPPQQQQQK..',
        '...KRSRRRRPPPPPPQQQQQK..',
        '..KRRRRRRPPPPPPPQQQQQQK.',
        '.KRRRRRRRPPPPPPPPQQQQQQK',
        '.KQSQQQQQQQQQQQQQQQQQQQK',
        'KQQQQQQQQQQQQQQQQQQQQQQQ',
        '.KKKKKKKKKKUTTKKKKKKKKKK',
        '..........KUTTK.........',
        '..........KUTTK.........',
        '..........KUTTK.........',
        '..........KUTTK.........',
        '..........KUTTK.........',
        '...........KKK..........',
      ],
    ],
  },
  'boulder': {
    id: 'boulder',
    width: 16,
    height: 16,
    palette: WORLD_PALETTE,
    frames: [
      [
        '................',
        '................',
        '................',
        '................',
        '.....KKKKKK.....',
        '...KKyyyyywKK...',
        '..KyyyyyywwwwK..',
        '.KyyAAyywwwwwwK.',
        '.KyyAywwwwzwwwK.',
        '.KyyyzwwwwwwxxK.',
        '.KyywwzwwwwxxxK.',
        '.KywwwwwwwxxxxK.',
        '.KwwwwwwwxxxxxK.',
        '..KxxxxxxxxxxK..',
        '...KKxxxxxxKK...',
        '.....KKKKKK.....',
      ],
    ],
  },
  'rock': {
    id: 'rock',
    width: 16,
    height: 16,
    palette: WORLD_PALETTE,
    frames: [
      [
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
        '.....KKKKKK.....',
        '....KyyyywwK....',
        '...KyyyywwwwK...',
        '...KyywwzwwxK...',
        '...KywwwwwxxK...',
        '...KwwwwwxxxK...',
        '....KxxxxxxK....',
        '.....KKKKKK.....',
      ],
    ],
  },
  'bush': {
    id: 'bush',
    width: 16,
    height: 16,
    palette: WORLD_PALETTE,
    frames: [
      [
        '................',
        '................',
        '................',
        '................',
        '................',
        '.....KKKKKK.....',
        '...KKllllljKK...',
        '..KlkllljjjjjK..',
        '.KlllFmkjjjjjjK.',
        '.KllllkjjFjmjmK.',
        '.KllljjjjkjjmmK.',
        '.KljjjjjjmmFmmK.',
        '.KjjjjjjjmmmmmK.',
        '..KmmkmmmmmmmK..',
        '...KKmmmmmmKK...',
        '.....KKKKKK.....',
      ],
    ],
  },
  'wreck': {
    id: 'wreck',
    width: 64,
    height: 40,
    palette: WORLD_PALETTE,
    frames: [
      [
        '................................................................',
        '................................................................',
        '................................................................',
        '................................................................',
        '................................................................',
        '...................................KK...........................',
        '.......KK.................KKKKKKKKKTUKKKKKKK....................',
        '......KHHK...............KTTTTTTTTTTTTTTTTTTK...................',
        '.....KHGXHK...............KWVVVVWVVVVWVVVVWK....................',
        '....KHGKKHK................KVWVWVVVVWVVVVWVK....................',
        '....KGK.KGK..............KKWVVWVVVVWVVVVWVK.....................',
        '....KGK..K.............KKWKVVWVVVYYVYVVWVVK.....................',
        '....KGK..............KKWKK.KWVVYYYYYVVWVVK......................',
        '.....K.............KKWKK..KWVVVVWYYYVWVVVK......................',
        '.................KKWKK....KVVVVWVVVVWVVVK.......................',
        '....K..........KKWKK.......KVVWVVVVWKVVVK.......................',
        '...KGKK......KKWKK........KVVWVVVVKVVVVK........................',
        '...KIGGK...KKWKK..........KVWVVVTWVVVVWK........................',
        '...KHIIGKKKWKK.............KVVKVWVVVVWK.........................',
        '...KGHHIGWKK..........KKKKKVKVVWVVVVWVKKKK......................',
        '...KIGGWIGGK...KKKKKKKGGGGGVVVWVVVVWVGGGGGKKKKKKK...............',
        '...KHIIGHIIGKKKGGGGGGGIIIIIIIITUIIIIIIIIIIGGGGGGGKKKKK..........',
        '...KGHHIGHHIGGGIIIIIIIHHHHHHHHTUHHHHHHHHHHIIIIIIIGGGGGK.........',
        '...KIGGHIGGHIIIHHHHHHHGGGGGGGGTUGGGGGGGGGGHHHHHHHIIIIIKK........',
        '...KHIIGHIIGHHHGGGGGGGIIIIIIIIIIIIIIIIIIIIGGGGGGGHHHHHGGKK..K...',
        '...KGHHIGHHIGGGIIIIIIIHHHHHHHHHHHHHHHHHHHHIIIIIIIGGGGGIIGGKKHK..',
        '...KIGGHIGGHIIIHHHHHHHGGGGGGGGGGGGGGGGGGGGHHHHHHHIIIIIHHIIHKK...',
        '...KHIIGHIIGHHHGGGGGGGIIIIIIIIIIIIIIIIIIIIGGGGGGGHHHHHGGHHGHK...',
        '...KGHHIGHHIGGGIIIIIIIHHHHHHHHHHHHHHHHHHHHIIIIIIIGGGGGIIGHIIK...',
        '...KIGGHIGGHIIIHHHHHHHGGGGGGGGGGGGGGGGGGGGHHHHHHHIIIIIHHIIHHK...',
        '...KHIIGHIIGHHHGGGGGGGIIIIIIIIIIIYIIIIIIIIGGGGGGGHHHHHGGHHGGK...',
        '...KGHHIGHHIGGGIIIIIIIHHHHHHHHHYYYYYHHHHHHIIIIIIIGGGGGIIGGIIK...',
        '...KHHGHIGGHIIIHHHHHHHGGGGGGGGYYYYYYGGGGGGHHHHHHHIIIIIHHIIHHK...',
        '...KHHHHHHIGHHHGGGGGGGIIIIIIIIIYYYYYIIIIIIGGGGGGGHHHHHHHHHHHK...',
        '....KKHHHHHHHHHHHIIIIIHHHHHHHHHHHHHHHHHHHHIIIIIHHHHHHHHHHHKK....',
        '......KKKKHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHKKKK......',
        '..........KKKKKKKHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHKKKKKKK..........',
        '.................KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK.................',
        '................................................................',
        '................................................................',
      ],
    ],
  },
}
