// GENERATED by tools/gen-tables from the table declarations in @bastion/core
// (CLAUDE.md 3.4) — DO NOT EDIT. Regenerate: pnpm --filter @bastion/gen-tables gen
// `pnpm build` and `pnpm test` fail when this file drifts from the declarations.

import { table, t } from 'spacetimedb/server'

export const tables = {
  counter: table(
    {
      name: 'counter',
      public: false,
    },
    {
      n: t.u64().primaryKey(),
      at: t.f64(),
    },
  ),
  every_type: table(
    {
      name: 'every_type',
      public: true,
      indexes: [
        { accessor: 'by_kind', algorithm: 'btree', columns: ['kind'] },
        { accessor: 'by_small_count', algorithm: 'btree', columns: ['small', 'count'] },
      ],
    },
    {
      id: t.string().primaryKey(),
      flag: t.bool(),
      small: t.i32(),
      count: t.u32(),
      big: t.i64(),
      ubig: t.u64(),
      ratio: t.f32(),
      x: t.f64(),
      whole: t.f64(),
      kind: t.string(),
      tag: t.string(),
      note: t.option(t.string()),
      list: t.array(t.i32()),
      stats: t.object('EveryTypeStats', { hp: t.f64(), resist: t.array(t.object('EveryTypeStatsResistItem', { element: t.string(), pct: t.f64() })) }),
      level: t.i32().default(1),
      label: t.string().default('it\'s'),
    },
  ),
} as const

/* gen-tables manifest: the append-only baseline for the next run. Do not edit.
{
  "counter": {
    "pk": "n",
    "columns": [
      {"name":"n","type":"u64"},
      {"name":"at","type":"f64"}
    ]
  },
  "every_type": {
    "pk": "id",
    "columns": [
      {"name":"id","type":"string"},
      {"name":"flag","type":"bool"},
      {"name":"small","type":"i32"},
      {"name":"count","type":"u32"},
      {"name":"big","type":"i64"},
      {"name":"ubig","type":"u64"},
      {"name":"ratio","type":"f32"},
      {"name":"x","type":"f64"},
      {"name":"whole","type":"f64"},
      {"name":"kind","type":"string"},
      {"name":"tag","type":"string"},
      {"name":"note","type":"option<string>"},
      {"name":"list","type":"array<i32>"},
      {"name":"stats","type":"{hp:f64,resist:array<{element:string,pct:f64}>}"},
      {"name":"level","type":"i32","default":true},
      {"name":"label","type":"string","default":true}
    ]
  }
}
*/
