// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const BuildInfo = __t.object("BuildInfo", {});
export type BuildInfo = __Infer<typeof BuildInfo>;

export const BuildInfoRow = __t.object("BuildInfoRow", {
  buildId: __t.string(),
});
export type BuildInfoRow = __Infer<typeof BuildInfoRow>;

export const CellDelta = __t.object("CellDelta", {
  key: __t.string(),
  cx: __t.f64(),
  cy: __t.f64(),
  sector: __t.string(),
  prop: __t.string(),
  hits: __t.f64(),
  owner: __t.string(),
});
export type CellDelta = __Infer<typeof CellDelta>;

export const CommandNonce = __t.object("CommandNonce", {
  sender: __t.string(),
  nonce: __t.f64(),
});
export type CommandNonce = __Infer<typeof CommandNonce>;

export const Entity = __t.object("Entity", {
  id: __t.i64(),
  kind: __t.string(),
  def: __t.string(),
  owner: __t.string(),
  level: __t.f64(),
  faction: __t.string(),
});
export type Entity = __Infer<typeof Entity>;

export const EntityInput = __t.object("EntityInput", {
  id: __t.i64(),
  ix: __t.f64(),
  iy: __t.f64(),
  moving: __t.bool(),
});
export type EntityInput = __Infer<typeof EntityInput>;

export const EntityPos = __t.object("EntityPos", {
  id: __t.i64(),
  x: __t.f64(),
  y: __t.f64(),
  vx: __t.f64(),
  vy: __t.f64(),
  facing: __t.f64(),
  sector: __t.string(),
});
export type EntityPos = __Infer<typeof EntityPos>;

export const EntitySeq = __t.object("EntitySeq", {
  name: __t.string(),
  next: __t.i64(),
});
export type EntitySeq = __Infer<typeof EntitySeq>;

export const Inventory = __t.object("Inventory", {
  key: __t.string(),
  owner: __t.string(),
  item: __t.string(),
  count: __t.f64(),
});
export type Inventory = __Infer<typeof Inventory>;

export const PlayerAction = __t.object("PlayerAction", {
  owner: __t.string(),
  readyTick: __t.f64(),
});
export type PlayerAction = __Infer<typeof PlayerAction>;

export const TickSchedule = __t.object("TickSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type TickSchedule = __Infer<typeof TickSchedule>;

export const WorldClock = __t.object("WorldClock", {
  id: __t.string(),
  tick: __t.f64(),
});
export type WorldClock = __Infer<typeof WorldClock>;

