// GENERATED by tools/gen-tables from the table declarations in @bastion/core
// (CLAUDE.md 3.4) — DO NOT EDIT. Regenerate: pnpm --filter @bastion/gen-tables gen
// `pnpm build` and `pnpm test` fail when this file drifts from the declarations.

import { table, t } from 'spacetimedb/server'

export const tables = {
  cell_delta: table(
    {
      name: 'cell_delta',
      public: true,
      indexes: [
        { accessor: 'by_sector', algorithm: 'btree', columns: ['sector'] },
      ],
    },
    {
      key: t.string().primaryKey(),
      cx: t.f64(),
      cy: t.f64(),
      sector: t.string(),
      prop: t.string(),
      hits: t.f64(),
      owner: t.string(),
    },
  ),
  command_nonce: table(
    {
      name: 'command_nonce',
      public: false,
    },
    {
      sender: t.string().primaryKey(),
      nonce: t.f64(),
    },
  ),
  entity: table(
    {
      name: 'entity',
      public: true,
      indexes: [
        { accessor: 'by_owner', algorithm: 'btree', columns: ['owner'] },
      ],
    },
    {
      id: t.i64().primaryKey(),
      kind: t.string(),
      def: t.string(),
      owner: t.string(),
      level: t.f64(),
      faction: t.string(),
    },
  ),
  entity_input: table(
    {
      name: 'entity_input',
      public: false,
      indexes: [
        { accessor: 'by_moving', algorithm: 'btree', columns: ['moving'] },
      ],
    },
    {
      id: t.i64().primaryKey(),
      ix: t.f64(),
      iy: t.f64(),
      moving: t.bool(),
    },
  ),
  entity_pos: table(
    {
      name: 'entity_pos',
      public: true,
      indexes: [
        { accessor: 'by_sector', algorithm: 'btree', columns: ['sector'] },
      ],
    },
    {
      id: t.i64().primaryKey(),
      x: t.f64(),
      y: t.f64(),
      vx: t.f64(),
      vy: t.f64(),
      facing: t.f64(),
      sector: t.string(),
    },
  ),
  entity_seq: table(
    {
      name: 'entity_seq',
      public: false,
    },
    {
      name: t.string().primaryKey(),
      next: t.i64(),
    },
  ),
  inventory: table(
    {
      name: 'inventory',
      public: true,
      indexes: [
        { accessor: 'by_owner', algorithm: 'btree', columns: ['owner'] },
      ],
    },
    {
      key: t.string().primaryKey(),
      owner: t.string(),
      item: t.string(),
      count: t.f64(),
    },
  ),
  player_action: table(
    {
      name: 'player_action',
      public: false,
    },
    {
      owner: t.string().primaryKey(),
      readyTick: t.f64(),
    },
  ),
  world_clock: table(
    {
      name: 'world_clock',
      public: true,
    },
    {
      id: t.string().primaryKey(),
      tick: t.f64(),
    },
  ),
} as const

/* gen-tables manifest: the append-only baseline for the next run. Do not edit.
{
  "cell_delta": {
    "pk": "key",
    "columns": [
      {"name":"key","type":"string"},
      {"name":"cx","type":"f64"},
      {"name":"cy","type":"f64"},
      {"name":"sector","type":"string"},
      {"name":"prop","type":"string"},
      {"name":"hits","type":"f64"},
      {"name":"owner","type":"string"}
    ]
  },
  "command_nonce": {
    "pk": "sender",
    "columns": [
      {"name":"sender","type":"string"},
      {"name":"nonce","type":"f64"}
    ]
  },
  "entity": {
    "pk": "id",
    "columns": [
      {"name":"id","type":"i64"},
      {"name":"kind","type":"string"},
      {"name":"def","type":"string"},
      {"name":"owner","type":"string"},
      {"name":"level","type":"f64"},
      {"name":"faction","type":"string"}
    ]
  },
  "entity_input": {
    "pk": "id",
    "columns": [
      {"name":"id","type":"i64"},
      {"name":"ix","type":"f64"},
      {"name":"iy","type":"f64"},
      {"name":"moving","type":"bool"}
    ]
  },
  "entity_pos": {
    "pk": "id",
    "columns": [
      {"name":"id","type":"i64"},
      {"name":"x","type":"f64"},
      {"name":"y","type":"f64"},
      {"name":"vx","type":"f64"},
      {"name":"vy","type":"f64"},
      {"name":"facing","type":"f64"},
      {"name":"sector","type":"string"}
    ]
  },
  "entity_seq": {
    "pk": "name",
    "columns": [
      {"name":"name","type":"string"},
      {"name":"next","type":"i64"}
    ]
  },
  "inventory": {
    "pk": "key",
    "columns": [
      {"name":"key","type":"string"},
      {"name":"owner","type":"string"},
      {"name":"item","type":"string"},
      {"name":"count","type":"f64"}
    ]
  },
  "player_action": {
    "pk": "owner",
    "columns": [
      {"name":"owner","type":"string"},
      {"name":"readyTick","type":"f64"}
    ]
  },
  "world_clock": {
    "pk": "id",
    "columns": [
      {"name":"id","type":"string"},
      {"name":"tick","type":"f64"}
    ]
  }
}
*/
