// GENERATED by tools/gen-tables from the table declarations in @bastion/core
// (CLAUDE.md 3.4) — DO NOT EDIT. Regenerate: pnpm --filter @bastion/gen-tables gen
// `pnpm build` and `pnpm test` fail when this file drifts from the declarations.

// No tables are declared yet.
export const tables = {} as const

/* gen-tables manifest: the append-only baseline for the next run. Do not edit.
{}
*/
