// GENERATED by tools/gen-tables from the table declarations in @bastion/core
// (CLAUDE.md 3.4) — DO NOT EDIT. Regenerate: pnpm --filter @bastion/gen-tables gen
// `pnpm build` and `pnpm test` fail when this file drifts from the declarations.

import { table, t } from 'spacetimedb/server'

export const tables = {
  command_nonce: table(
    {
      name: 'command_nonce',
      public: true,
    },
    {
      sender: t.string().primaryKey(),
      nonce: t.f64(),
    },
  ),
} as const

/* gen-tables manifest: the append-only baseline for the next run. Do not edit.
{
  "command_nonce": {
    "pk": "sender",
    "columns": [
      {"name":"sender","type":"string"},
      {"name":"nonce","type":"f64"}
    ]
  }
}
*/
