// Table declarations -> the text of `packages/server/src/tables.ts`.
//
// Output is a pure function of the declarations: tables sorted by name,
// columns in declaration order (their order is the stored row layout), indexes
// in declaration order. The file ends with a manifest of every table's pk and
// column types, which the next run reads to enforce append-only (3.4).

import type { TableDef } from '@bastion/core'
import {
  GenError,
  INDEXABLE,
  mapColumn,
  objectNames,
  quote,
  renderLiteral,
  renderType,
  typeKey,
  type Column,
} from './columns.ts'

export { GenError } from './columns.ts'

export interface ManifestColumn {
  readonly name: string
  readonly type: string
  readonly default?: true
}
export interface ManifestTable {
  readonly pk: string
  readonly columns: readonly ManifestColumn[]
}
export type Manifest = Readonly<Record<string, ManifestTable>>

export interface Generated {
  readonly source: string
  readonly manifest: Manifest
}

const HEADER = `// GENERATED by tools/gen-tables from the table declarations in @bastion/core
// (CLAUDE.md 3.4) — DO NOT EDIT. Regenerate: pnpm --filter @bastion/gen-tables gen
// \`pnpm build\` and \`pnpm test\` fail when this file drifts from the declarations.
`

const MANIFEST_OPEN = '/* gen-tables manifest: the append-only baseline for the next run. Do not edit.'
const MANIFEST = /\/\* gen-tables manifest:[^\n]*\n([\s\S]*?)\n\*\//

interface Mapped {
  readonly def: TableDef
  readonly columns: readonly Column[]
}

function mapTable(def: TableDef): Mapped {
  const columns = Object.entries(def.row.shape).map(([name, schema]) =>
    mapColumn(def.name, name, schema as unknown as Parameters<typeof mapColumn>[2]),
  )
  const byName = new Map(columns.map((c) => [c.name, c]))
  const pk = byName.get(def.pk)!
  if (!INDEXABLE.has(pk.type.kind)) {
    throw new GenError(
      `${def.name}.${def.pk}: primary key maps to ${typeKey(pk.type)}; use z.string(), z.int32(), z.uint32(), z.bigint() or z.uint64()`,
    )
  }
  if (pk.default !== undefined) throw new GenError(`${def.name}.${def.pk}: a primary key cannot have a .default()`)
  for (const index of def.indexes) {
    for (const column of index.columns) {
      const type = byName.get(column)!.type
      if (!INDEXABLE.has(type.kind)) {
        throw new GenError(
          `${def.name}.${column}: index "${index.name}" needs an indexable column, got ${typeKey(type)} (use z.int32()/z.uint32() for numbers)`,
        )
      }
    }
  }
  return { def, columns }
}

function renderTable({ def, columns }: Mapped): string {
  const opts = [`      name: ${quote(def.name)},`, `      public: ${def.public},`]
  if (def.indexes.length > 0) {
    opts.push('      indexes: [')
    for (const ix of def.indexes) {
      const cols = ix.columns.map(quote).join(', ')
      opts.push(`        { accessor: ${quote(ix.name)}, algorithm: 'btree', columns: [${cols}] },`)
    }
    opts.push('      ],')
  }
  const cols = columns.map((c) => {
    let expr = renderType(c.type)
    if (c.name === def.pk) expr += '.primaryKey()'
    if (c.default !== undefined) expr += `.default(${renderLiteral(c.default)})`
    return `      ${c.name}: ${expr},`
  })
  return `  ${def.name}: table(\n    {\n${opts.join('\n')}\n    },\n    {\n${cols.join('\n')}\n    },\n  ),`
}

function manifestOf(mapped: readonly Mapped[]): Manifest {
  const out: Record<string, ManifestTable> = {}
  for (const { def, columns } of mapped) {
    out[def.name] = {
      pk: def.pk,
      columns: columns.map((c) => ({
        name: c.name,
        type: typeKey(c.type),
        ...(c.default !== undefined ? { default: true as const } : {}),
      })),
    }
  }
  return out
}

/** Generate the server table file from declarations (any order; output is sorted). */
export function generate(defs: readonly TableDef[]): Generated {
  const sorted = [...defs].sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0))
  const mapped = sorted.map(mapTable)
  const owners = new Map<string, string>()
  for (const { def, columns } of mapped) {
    for (const name of columns.flatMap((c) => objectNames(c.type))) {
      const other = owners.get(name)
      if (other !== undefined && other !== def.name) {
        throw new GenError(`${def.name}: nested type name "${name}" collides with one in table "${other}"`)
      }
      owners.set(name, def.name)
    }
  }
  const manifest = manifestOf(mapped)
  const body =
    mapped.length === 0
      ? '// No tables are declared yet.\nexport const tables = {} as const\n'
      : `import { table, t } from 'spacetimedb/server'\n\nexport const tables = {\n${mapped.map(renderTable).join('\n')}\n} as const\n`
  const source = `${HEADER}\n${body}\n${MANIFEST_OPEN}\n${renderManifest(manifest)}\n*/\n`
  return { source, manifest }
}

/** JSON with one column per line, so a schema change reads as a small diff. */
function renderManifest(manifest: Manifest): string {
  const tables = Object.entries(manifest).map(([name, { pk, columns }]) => {
    const cols = columns.map((c) => `      ${JSON.stringify(c)}`).join(',\n')
    return `  ${JSON.stringify(name)}: {\n    "pk": ${JSON.stringify(pk)},\n    "columns": [\n${cols}\n    ]\n  }`
  })
  return tables.length === 0 ? '{}' : `{\n${tables.join(',\n')}\n}`
}

/** Read the manifest out of a previously generated file; `{}` when there is none. */
export function parseManifest(source: string): Manifest {
  const m = MANIFEST.exec(source)
  return m ? (JSON.parse(m[1]!) as Manifest) : {}
}

/**
 * Append-only (CLAUDE.md 3.4): every table in `prev` still exists with the same
 * pk, its columns are an unchanged prefix of the new ones (no removal, rename,
 * retype or reorder), and a column appended to an existing table is optional
 * or has a default. Returns one message per violation.
 */
export function checkAppendOnly(prev: Manifest, next: Manifest): string[] {
  const errors: string[] = []
  for (const [name, old] of Object.entries(prev)) {
    const cur = next[name]
    if (!cur) {
      errors.push(`${name}: table was removed`)
      continue
    }
    if (cur.pk !== old.pk) errors.push(`${name}: primary key changed from ${old.pk} to ${cur.pk}`)
    old.columns.forEach((col, i) => {
      const now = cur.columns[i]
      const where = `${name}.${col.name}`
      if (!now) errors.push(`${where}: column was removed`)
      else if (now.name !== col.name) errors.push(`${where}: column #${i + 1} is now "${now.name}" (removed, renamed or reordered)`)
      else if (now.type !== col.type) errors.push(`${where}: type changed from ${col.type} to ${now.type}`)
    })
    for (const col of cur.columns.slice(old.columns.length)) {
      if (!col.default && !col.type.startsWith('option<')) {
        errors.push(`${name}.${col.name}: a column appended to an existing table must be .optional() or have a .default()`)
      }
    }
  }
  return errors
}
