import { createHash } from 'node:crypto'

const HEADER = /^<!-- generated by `pnpm tasks:(\w+)` — do not edit by hand\. content-hash: ([0-9a-f]{16}) -->\n/

const digest = (body: string): string => createHash('sha256').update(body).digest('hex').slice(0, 16)

/** Prefix a generated document with its header line and content hash. */
export function withHash(cmd: string, body: string): string {
  return `<!-- generated by \`pnpm tasks:${cmd}\` — do not edit by hand. content-hash: ${digest(body)} -->\n${body}`
}

/** 'ok', or why the file is not an untouched generated document. */
export function checkHash(text: string): string {
  const m = HEADER.exec(text)
  if (!m) return 'missing generated header'
  return digest(text.slice(m[0].length)) === m[2] ? 'ok' : 'content hash mismatch (hand-edited?)'
}
