// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import BuildReducer from "../build_reducer";
import HarvestReducer from "../harvest_reducer";
import JoinReducer from "../join_reducer";
import MoveReducer from "../move_reducer";

export type BuildParams = __Infer<typeof BuildReducer>;
export type HarvestParams = __Infer<typeof HarvestReducer>;
export type JoinParams = __Infer<typeof JoinReducer>;
export type MoveParams = __Infer<typeof MoveReducer>;

